blank_issues_enabled: true
contact_links:
  - name: Add new ToDo
    about: made by config.yml
    # edit {username} and {repo} for your environment
    url: https://github.com/RyunosukeSekido/laravel-vue-docker-base/issues/new?template=custom.md&projects=RyunosukeSekido%2FToDo%2F5&labels=ToDo
